### ISSUE TITLE
EnderCore causing some SpongeForge plugins to stop working

### ISSUE THREAD

**Issue by rob5251** [SleepyTrousers/EnderCore#36]
While using EnderCore on a SpongeForge server it will cause some Sponge plugins to loose functionality (Cant use the commands)

I have documented this issue in more detail on my thread over on the Sponge forums.
https://forums.spongepowered.org/t/plugin-issue-not-loading-commands-not-working/12170/5

Not sure if this is something to be fixed by Sponge, the plugin developers, or EnderCore.
I figured I would bring this to your attention though so your mods can play nice with Sponge in the future.

**Comment by HenryLoenwind** [comment]
If this was all plugin commands, I'd look into this. But it's only some of them. So I suspect they are doing some funky black magic to register their commands. EnderCore does not; it uses the normal Forge command registry to register its commands.

**Comment by rob5251** [comment]
Must be, I suppose the issue has to be fixed by the plugin developers then. As I said in my post over on the Sponge forums, Prism did continue to work fine throughout.

**Comment by HenryLoenwind** [comment]
There's a good chance ec is the only mod you have that registers commands. Not many mods do...

**Comment by jpiermarini** [comment]
I'm having this issue with both essentialscmd and PermissionsEx, but it only happens when endercore is loaded on the server. 

My assumption is it's a sponge issue. I created an issue with them at https://github.com/SpongePowered/SpongeForge/issues/610 and if you are intersted in taking a peak at my log file it is here https://paste.ee/p/rVF57/   

Hoping it gets resolved was very excited when I saw EnderIO was out for 1.8.9
